
//Include guard for DUMMY_FEAT_H
#ifndef DUMMY_FEAT_H
#define DUMMY_FEAT_H

//Necessery includes, the header for the Ui code generated by Qt and the interface through
//witch to communicate with the main program
#include "ui_dummyFeat.h"
#include "ccStdPluginInterface.h"

//Include the Qt features used
#include <QMainWindow>
#include <QDialog>

class ccDummyFeat : public QDialog, public Ui::dummyFeat
{
	Q_OBJECT //Important; lets Qt know to edit this code

public:
	//Constructor and Destructor declarations
	ccDummyFeat(QWidget* parent = 0, ccMainAppInterface* = 0);
	~ccDummyFeat();

protected slots:
	//Protected slots is a feature of Qt, methods that will be connected to
	//QObjects must be declared here!
	void helloWorld();

private:
	//declaration of the main app interface
	ccMainAppInterface* m_app;

};

#endif //Include guard for DUMMY_FEAT_H
